name: first
on:
    push:
        branches:
            - main

env:
    env_scope: "global-var"
jobs:
    runcommand-job1:
        runs-on: ubuntu-latest
        env:
            env_scope: "job"
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Run the single commands
              run: |
                echo "Hello world 1"
                echo "scope: ${{ env.env_scope }}"
                echo "job: ${{ env.job }} "
                echo "step: ${{ env.step }} "
            - name: Run the multiple commands
              env:
                step: "checkout"
                env_scope: "step"
              run: |
                echo "This is multiple line command"
                echo "scope: ${{ env.env_scope }}"
                echo "job: ${{ env.job }}"
                echo "step: ${{ env.step }}"

    # runcommand-job2:
    #     runs-on: ubuntu-latest
    #     needs: [runcommands]
    #     steps:
    #         - name: Checkout the code
    #           uses: actions/checkout@v4

    #         - name: Run the commands
    #           run: echo "Hello world"

    #         - name: Run the multiple commands
    #           run: |
    #             echo "Hello world 1"
    #             echo "Hello world 2"