name: first
on:
    push
env:
    env_scope: "global variable"
jobs:
    runcommand-job1:
        runs-on: ubuntu-latest
        env:
            env_scope: "job variable"
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Run the mulltiple commands 1
              run: |
                echo "Hello world 1"
                echo "scope: ${{ env.env_scope }}"
                echo "scope: ${{ env.job }}"
                echo "scope: ${{ env.step }}"


            - name: Run the multiple commands 2
              env:
                env_scope: "step variable"
              run: |
                echo "Hello world 2"
                echo "scope: ${{ env.env_scope }}"
                echo "scope: ${{ env.job }}"
                echo "scope: ${{ env.step }}"

    # runcommand-job2:
    #     runs-on: ubuntu-latest
    #     needs: [runcommands]
    #     steps:
    #         - name: Checkout the code
    #           uses: actions/checkout@v4

    #         - name: Run the commands
    #           run: echo "Hello world"

    #         - name: Run the multiple commands
    #           run: |
    #             echo "Hello world 1"
    #             echo "Hello world 2"